sonar.organization=alouirahma
sonar.projectKey=alouirahma_devmedic
sonar.sources=devMedic/ms-Backend
sonar.exclusions=**/target/**,**/node_modules/**,**/*.test.ts
sonar.java.binaries=devMedic/ms-Backend/gestionGit/target/classes,devMedic/ms-Backend/gestionUser/target/classes