apiVersion: v1
kind: Secret
metadata:
  name: devmedic-secrets
type: Opaque
data:
  KEYCLOAK_DB_PASSWORD: a2V5Y2xvYWsxMjM=
  KEYCLOAK_ADMIN_PASSWORD: cmFobWExMjM=
  POSTGRES_APP_PASSWORD: cG9zdGdyZXMxMjM=
  SONAR_TOKEN: c3F1XzQ3ZjRlZjQ0NzU5OTMzYTBiMjJjMmMzMDlmZDBiY2IyYjhjNmFhMTg=