# ====================== SERVER ======================
server.port=8081

# ====================== APPLICATION ======================
spring.application.name=gestion-user
# =========================================================
keycloak.admin.url=http://keycloak:8080
keycloak.admin.username=admin
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD}
keycloak.realm=devmedic
# ====================== DATABASE ======================
spring.datasource.url=jdbc:postgresql://postgres-app:5432/devmedic
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_APP_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ====================== JPA ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ====================== KEYCLOAK (IMPORTANT FIX) ======================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://auth.localhost/realms/devmedic
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/devmedic/protocol/openid-connect/certs
keycloak.auth-server-url=http://keycloak:8080

# ====================== EUREKA (AJOUT OBLIGATOIRE) ======================
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=gestion-user
eureka.instance.prefer-ip-address=false
# ====================== SWAGGER ======================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.oauth2-redirect-url=http://localhost:8081/swagger-ui/oauth2-redirect.html
springdoc.swagger-ui.oauth-client-id=gestion-user
springdoc.swagger-ui.oauth-use-pkce=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha

# URL du microservice gestion-git
git.service.url=http://localhost:8082

#Health checks
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always